language: node_js
node_js:
  - "18"
dist: focal
script:
  - npm test

deploy:
  provider: pages
  token: $toki  # Reference the environment variable "toki" set in Travis CI
  keep_history: true
  local_dir: build
  on:
    branch: main

before_install:
  - nvm install 18
  - nvm use 18
install:
  - npm install
